### ISSUE TITLE
.pkl file read error

### ISSUE THREAD

**Issue by Xinchengzelin** [Henry1iu/TNT-Trajectory-Prediction#41]
Hi,  I want to know the what the data looks like, so I use `pd.read_pickle("features_6024.pkl")` to read the raw `.pkl` data. However, I install python==3.8.8 and pandas==1.2.4/1.0.0 ,  any of the pandas version failed to read this pkl file, the error shows as below:
```
>>> data = pd.read_pickle("features_6024.pkl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zetlin/miniconda3/envs/argo/lib/python3.8/site-packages/pandas/io/pickle.py", line 208, in read_pickle
    return pc.load(handles.handle, encoding=None)
  File "/home/zetlin/miniconda3/envs/argo/lib/python3.8/site-packages/pandas/compat/pickle_compat.py", line 249, in load
    return up.load()
  File "/home/zetlin/miniconda3/envs/argo/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/zetlin/miniconda3/envs/argo/lib/python3.8/pickle.py", line 1537, in load_stack_global
    self.append(self.find_class(module, name))
  File "/home/zetlin/miniconda3/envs/argo/lib/python3.8/site-packages/pandas/compat/pickle_compat.py", line 189, in find_class
    return super().find_class(module, name)
  File "/home/zetlin/miniconda3/envs/argo/lib/python3.8/pickle.py", line 1581, in find_class
    return _getattribute(sys.modules[module], name)[0]
  File "/home/zetlin/miniconda3/envs/argo/lib/python3.8/pickle.py", line 331, in _getattribute
    raise AttributeError("Can't get attribute {!r} on {!r}"
AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/zetlin/miniconda3/envs/argo/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>

```

Could you explain more about the data?
1. How to generate the candidates?
2. What is gt['target_prob'], target['offset']? Could you explain more how to calculate this?

**Comment by Henry1iu** [comment]
Hi,

Sorry for this issue. The small dataset is generated by version 1.4.4. I'll correct it in my readme and requirements.txt. 

As for the explanation,

1. find the possible routes for the target agent. Then, sample points along these possible routes with equal distances.
2. gt['target_prob'] is the ground truth distribution of the target position; target['offset'] is the predicted x,y offset with respect to the selected target position. As for the calculation, you can refer to the original paper of TNT.

Best Regards,
Jianbang
